parameters:
#    app_helper.example.class: App\HelperBundle\Example

services:
#    app_helper.example:
#        class: %app_helper.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
