<?php

namespace Data\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlikTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlikTaskRepository extends EntityRepository
{
    
}
