<?php

namespace Data\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlikWiadomosciRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlikWiadomosciRepository extends EntityRepository
{
    
                    public function deleteMessagePliki(String $message_id) {
       $this->getEntityManager()
                ->createQueryBuilder()
                ->delete('DataDatabaseBundle:PlikiWiadomosci', 'u')
                ->where('u.projekt_id = '.$message_id)
                ->getQuery()
                ->execute();
    }
}
