<?php

namespace Data\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlikTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlikTaskRepository extends EntityRepository
{
    
        
            public function deleteTaskPliki(String $task_id) {
       $this->getEntityManager()
                ->createQueryBuilder()
                ->delete('DataDatabaseBundle:PlikiTask', 'u')
                ->where('u.projekt_id = '.$task_id)
                ->getQuery()
                ->execute();
    }
}
