<?php

namespace Data\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RkOperacjaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RkOperacjaRepository extends EntityRepository {
    
    public function getAllKwota($confirm = false) {
        $query = $this->getEntityManager()->createQuery("
            SELECT SUM(rk.kwotaNetto)
                FROM DataDatabaseBundle:RkOperacja rk
                WHERE rk.confirm = :confirm
        ");
        $query->setParameter(":confirm", $confirm);
        return $query->getSingleResult();
    }
    
    
}
