<?php

namespace Data\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    
            public function getTaskIdFromProjekt(Projekt $projekt) {
              $db = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('g')
                 ->from('DataDatabaseBundle:Task','g')
                 ->where('g.projekt_id =' . $projekt->getId())   
                ->getQuery();
            
              return  $db ;
    }
    
            public function deleteTask(String $task_id) {
       $this->getEntityManager()
                ->createQueryBuilder()
                ->delete('DataDatabaseBundle:Task', 'u')
                ->where('u.projekt_id = '.$id)
                ->getQuery()
                ->execute();
    }
}
