<?php

namespace Data\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WiadomoscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WiadomoscRepository extends EntityRepository
{
                public function getMessageIdFromTask(String $task_id) {
              $db = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('g')
                 ->from('DataDatabaseBundle:Wiadomosc','g')
                 ->where('g.projekt_id =' . $task_id)   
                ->getQuery();
            
              return  $db ;
    }
    
                        public function deleteMessage(String $task_id) {
       $this->getEntityManager()
                ->createQueryBuilder()
                ->delete('DataDatabaseBundle:PlikiWiadomosci', 'u')
                ->where('u.projekt_id = '.$task_id)
                ->getQuery()
                ->execute();
    }
}
