<?php

namespace Data\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WiadomoscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WiadomoscRepository extends EntityRepository {

    public function deleteMessage(String $message_id) {
        $this->getEntityManager()
                ->createQueryBuilder()
                ->delete('DataDatabaseBundle:Wiadomosc', 'u')
                ->where('u.id = ' . $message_id)
                ->getQuery()
                ->execute();
    }

}
